name: domain_bridge_pinky3
topics:
  # ---------------- Pinkyb44f (34) -> Laptop (30) ----------------
  /pinky3/obstacle_detected:
    from_domain: 34
    to_domain: 30
    type: std_msgs/msg/Bool

  /pinky3/robot_state:
    from_domain: 34
    to_domain: 30
    type: pinky_interfaces/msg/RobotState

  /pinky3/battery_voltage:
    from_domain: 34
    to_domain: 30
    type: std_msgs/msg/Float32

  /pinky3/cmd_vel:
    from_domain: 34
    to_domain: 30
    type: geometry_msgs/msg/Twist

  /pinky3/mission_result:
    from_domain: 34
    to_domain: 30
    type: std_msgs/msg/String

  # MapWall JSON
  /pinky3/debug/walls_xy_json:
    from_domain: 34
    to_domain: 30
    type: std_msgs/msg/String

  # ✅ TF (pinky2 only)
  /tf:
    from_domain: 34
    to_domain: 30
    type: tf2_msgs/msg/TFMessage

  /tf_static:
    from_domain: 34
    to_domain: 30
    type: tf2_msgs/msg/TFMessage

  # ---------------- Laptop (30) -> Pinkyb44f (34) ----------------
  /traffic/mission_request:    # 상대이름으로 바꿀땐 /pinky3/mission_request
    from_domain: 30
    to_domain: 34
    type: std_msgs/msg/String

  /traffic/mission_cancel:      # 상대이름으로 바꿀땐 /pinky3/mission_cancel
    from_domain: 30
    to_domain: 34
    type: std_msgs/msg/String

  # AvoidDecision 결과 -> 로봇
  /pinky3/vision/avoid_dir_json:
    from_domain: 30
    to_domain: 34
    type: std_msgs/msg/String
